// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _example_t_h
#define _example_t_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _example_t example_t;
struct _example_t
{
    int64_t    utime;
    float      trans_v;
    /// in m/s
    float      angular_v;
};

/**
 * Create a deep copy of a example_t.
 * When no longer needed, destroy it with example_t_destroy()
 */
example_t* example_t_copy(const example_t* to_copy);

/**
 * Destroy an instance of example_t created by example_t_copy()
 */
void example_t_destroy(example_t* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _example_t_subscription_t example_t_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * example_t is received.
 */
typedef void(*example_t_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const example_t *msg, void *userdata);

/**
 * Publish a message of type example_t using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int example_t_publish(lcm_t *lcm, const char *channel, const example_t *msg);

/**
 * Subscribe to messages of type example_t using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
example_t_subscription_t* example_t_subscribe(
    lcm_t *lcm, const char *channel, example_t_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by example_t_subscribe()
 */
int example_t_unsubscribe(lcm_t *lcm, example_t_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int example_t_subscription_set_queue_capacity(
    example_t_subscription_t* subs, int num_messages);

/**
 * Encode a message of type example_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to example_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int example_t_encode(void *buf, int offset, int maxlen, const example_t *p);

/**
 * Decode a message of type example_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with example_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int example_t_decode(const void *buf, int offset, int maxlen, example_t *msg);

/**
 * Release resources allocated by example_t_decode()
 * @return 0
 */
int example_t_decode_cleanup(example_t *p);

/**
 * Check how many bytes are required to encode a message of type example_t
 */
int example_t_encoded_size(const example_t *p);

// LCM support functions. Users should not call these
int64_t __example_t_get_hash(void);
uint64_t __example_t_hash_recursive(const __lcm_hash_ptr *p);
int __example_t_encode_array(
    void *buf, int offset, int maxlen, const example_t *p, int elements);
int __example_t_decode_array(
    const void *buf, int offset, int maxlen, example_t *p, int elements);
int __example_t_decode_array_cleanup(example_t *p, int elements);
int __example_t_encoded_array_size(const example_t *p, int elements);
int __example_t_clone_array(const example_t *p, example_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
