// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "robot_store_t.h"

static int __robot_store_t_hash_computed;
static uint64_t __robot_store_t_hash;

uint64_t __robot_store_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __robot_store_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __robot_store_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xb3664a0bbb5082b7LL
         + __string_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __robot_store_t_get_hash(void)
{
    if (!__robot_store_t_hash_computed) {
        __robot_store_t_hash = (int64_t)__robot_store_t_hash_recursive(NULL);
        __robot_store_t_hash_computed = 1;
    }

    return __robot_store_t_hash;
}

int __robot_store_t_encode_array(void *buf, int offset, int maxlen, const robot_store_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].command), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].value), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int robot_store_t_encode(void *buf, int offset, int maxlen, const robot_store_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __robot_store_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __robot_store_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __robot_store_t_encoded_array_size(const robot_store_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __string_encoded_array_size(&(p[element].command), 1);

        size += __float_encoded_array_size(&(p[element].value), 1);

    }
    return size;
}

int robot_store_t_encoded_size(const robot_store_t *p)
{
    return 8 + __robot_store_t_encoded_array_size(p, 1);
}

int __robot_store_t_decode_array(const void *buf, int offset, int maxlen, robot_store_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].command), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].value), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __robot_store_t_decode_array_cleanup(robot_store_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __string_decode_array_cleanup(&(p[element].command), 1);

        __float_decode_array_cleanup(&(p[element].value), 1);

    }
    return 0;
}

int robot_store_t_decode(const void *buf, int offset, int maxlen, robot_store_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __robot_store_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __robot_store_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int robot_store_t_decode_cleanup(robot_store_t *p)
{
    return __robot_store_t_decode_array_cleanup(p, 1);
}

int __robot_store_t_clone_array(const robot_store_t *p, robot_store_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __string_clone_array(&(p[element].command), &(q[element].command), 1);

        __float_clone_array(&(p[element].value), &(q[element].value), 1);

    }
    return 0;
}

robot_store_t *robot_store_t_copy(const robot_store_t *p)
{
    robot_store_t *q = (robot_store_t*) malloc(sizeof(robot_store_t));
    __robot_store_t_clone_array(p, q, 1);
    return q;
}

void robot_store_t_destroy(robot_store_t *p)
{
    __robot_store_t_decode_array_cleanup(p, 1);
    free(p);
}

int robot_store_t_publish(lcm_t *lc, const char *channel, const robot_store_t *p)
{
      int max_data_size = robot_store_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = robot_store_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _robot_store_t_subscription_t {
    robot_store_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void robot_store_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    robot_store_t p;
    memset(&p, 0, sizeof(robot_store_t));
    status = robot_store_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding robot_store_t!!!\n", status);
        return;
    }

    robot_store_t_subscription_t *h = (robot_store_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    robot_store_t_decode_cleanup (&p);
}

robot_store_t_subscription_t* robot_store_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    robot_store_t_handler_t f, void *userdata)
{
    robot_store_t_subscription_t *n = (robot_store_t_subscription_t*)
                       malloc(sizeof(robot_store_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 robot_store_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg robot_store_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int robot_store_t_subscription_set_queue_capacity (robot_store_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int robot_store_t_unsubscribe(lcm_t *lcm, robot_store_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe robot_store_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

