all:
	$(MAKE) -C gridworld
	$(MAKE) -C benchmarks
	$(MAKE) -C beta_bernoulli
	$(MAKE) -C coin
	$(MAKE) -C ds
	$(MAKE) -C gaussian_gaussian
	$(MAKE) -C geometric
	echo "Ignore:" $(MAKE) -C gym-cartpole
	echo "Ignore:" $(MAKE) -C heater
	$(MAKE) -C hiking
	$(MAKE) -C hmm
	$(MAKE) -C hmm_multi_sensors
	$(MAKE) -C ilmdp
	$(MAKE) -C line
	$(MAKE) -C mv_gaussian
	$(MAKE) -C pid
	$(MAKE) -C restaurants
	$(MAKE) -C slam
	$(MAKE) -C walker

clean:
	$(MAKE) -C gridworld clean
	$(MAKE) -C benchmarks clean
	$(MAKE) -C beta_bernoulli clean
	$(MAKE) -C coin clean
	$(MAKE) -C ds clean
	$(MAKE) -C gaussian_gaussian clean
	$(MAKE) -C geometric clean
	$(MAKE) -C gym-cartpole clean
	$(MAKE) -C heater clean
	$(MAKE) -C hiking clean
	$(MAKE) -C hmm clean
	$(MAKE) -C hmm_multi_sensors clean
	$(MAKE) -C ilmdp clean
	$(MAKE) -C line clean
	$(MAKE) -C mv_gaussian clean
	$(MAKE) -C pid clean
	$(MAKE) -C restaurants clean
	$(MAKE) -C slam clean
	$(MAKE) -C walker clean

realclean cleanall:
	$(MAKE) -C gridworld cleanall
	$(MAKE) -C benchmarks cleanall
	$(MAKE) -C beta_bernoulli cleanall
	$(MAKE) -C coin cleanall
	$(MAKE) -C ds cleanall
	$(MAKE) -C gaussian_gaussian cleanall
	$(MAKE) -C geometric cleanall
	$(MAKE) -C gym-cartpole cleanall
	$(MAKE) -C heater cleanall
	$(MAKE) -C hiking cleanall
	$(MAKE) -C hmm cleanall
	$(MAKE) -C hmm_multi_sensors cleanall
	$(MAKE) -C ilmdp cleanall
	$(MAKE) -C line cleanall
	$(MAKE) -C mv_gaussian cleanall
	$(MAKE) -C pid cleanall
	$(MAKE) -C restaurants cleanall
	$(MAKE) -C slam cleanall
	$(MAKE) -C walker cleanall
	-rm -f *~
