all:
	$(MAKE) -C gridworld
	$(MAKE) -C coin
	$(MAKE) -C heater
	$(MAKE) -C hiking
	$(MAKE) -C hmm
	$(MAKE) -C ilmdp
	$(MAKE) -C line
	$(MAKE) -C pid
	$(MAKE) -C restaurants

clean:
	$(MAKE) -C gridworld clean
	$(MAKE) -C coin clean
	$(MAKE) -C heater clean
	$(MAKE) -C hiking clean
	$(MAKE) -C hmm clean
	$(MAKE) -C ilmdp clean
	$(MAKE) -C line clean
	$(MAKE) -C pid clean
	$(MAKE) -C restaurants clean

realclean cleanall:
	$(MAKE) -C gridworld cleanall
	$(MAKE) -C coin cleanall
	$(MAKE) -C heater cleanall
	$(MAKE) -C hiking cleanall
	$(MAKE) -C hmm cleanall
	$(MAKE) -C ilmdp cleanall
	$(MAKE) -C line cleanall
	$(MAKE) -C pid cleanall
	$(MAKE) -C restaurants cleanall
	-rm -f *~
