// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _robot_store_t_h
#define _robot_store_t_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _robot_store_t robot_store_t;
struct _robot_store_t
{
    /// int64_t utime;
    char*      command;
    /// command identification
    float      value;
};

/**
 * Create a deep copy of a robot_store_t.
 * When no longer needed, destroy it with robot_store_t_destroy()
 */
robot_store_t* robot_store_t_copy(const robot_store_t* to_copy);

/**
 * Destroy an instance of robot_store_t created by robot_store_t_copy()
 */
void robot_store_t_destroy(robot_store_t* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _robot_store_t_subscription_t robot_store_t_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * robot_store_t is received.
 */
typedef void(*robot_store_t_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const robot_store_t *msg, void *userdata);

/**
 * Publish a message of type robot_store_t using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int robot_store_t_publish(lcm_t *lcm, const char *channel, const robot_store_t *msg);

/**
 * Subscribe to messages of type robot_store_t using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
robot_store_t_subscription_t* robot_store_t_subscribe(
    lcm_t *lcm, const char *channel, robot_store_t_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by robot_store_t_subscribe()
 */
int robot_store_t_unsubscribe(lcm_t *lcm, robot_store_t_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int robot_store_t_subscription_set_queue_capacity(
    robot_store_t_subscription_t* subs, int num_messages);

/**
 * Encode a message of type robot_store_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to robot_store_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int robot_store_t_encode(void *buf, int offset, int maxlen, const robot_store_t *p);

/**
 * Decode a message of type robot_store_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with robot_store_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int robot_store_t_decode(const void *buf, int offset, int maxlen, robot_store_t *msg);

/**
 * Release resources allocated by robot_store_t_decode()
 * @return 0
 */
int robot_store_t_decode_cleanup(robot_store_t *p);

/**
 * Check how many bytes are required to encode a message of type robot_store_t
 */
int robot_store_t_encoded_size(const robot_store_t *p);

// LCM support functions. Users should not call these
int64_t __robot_store_t_get_hash(void);
uint64_t __robot_store_t_hash_recursive(const __lcm_hash_ptr *p);
int __robot_store_t_encode_array(
    void *buf, int offset, int maxlen, const robot_store_t *p, int elements);
int __robot_store_t_decode_array(
    const void *buf, int offset, int maxlen, robot_store_t *p, int elements);
int __robot_store_t_decode_array_cleanup(robot_store_t *p, int elements);
int __robot_store_t_encoded_array_size(const robot_store_t *p, int elements);
int __robot_store_t_clone_array(const robot_store_t *p, robot_store_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
