#!/bin/sh

# Plot the differences between values in two data files.

ME=`basename $0`
TOOLS=`dirname $0`

## Process arguments

usage() { cat 1>&2 <<EOF
usage: ${ME} file1.dat file2.dat > plot.pdf

options:
  -t s | --title s	a title for the graphs
  -c x | --columns x	number of columns of graphs
  -r x | --rows x	number of rows of graphs
  --together		also plot matching columns together
  --monochrome		plot in black and white
  -h | --help           show this message
EOF
}

TITLE=""
GROWS=2
GCOLS=2
MODES="0"

TERMOPTIONS=""

while [ "$1" ] ; do
    case $1 in
    -t | --title)
	shift
	TITLE="$1"
	;;

    -c | --columns)
	shift
	GCOLS=$1
	;;

    -r | --rows)
	shift
	GROWS=$1
	;;

    --together)
	MODES="0 1"
	;;

    --monochrome)
	TERMOPTIONS="${TERMOPTIONS} mono dashed"
	;;

    -h | --help )

	usage
	exit
	;;

    -* )
	printf "${ME}: unknown option \(ignored\): $1\n" 2>&1
	;;
    *)
	if [ -z "${FILE1}" ]; then
	    FILE1=$1
	    FILENAME1=${FILE1}
	elif [ -z "${FILE2}" ]; then
	    FILE2=$1
	    FILENAME2=${FILE2}
	else
	    printf "${ME}: too many filenames \(ignored\): $1\n" 2>&1
	fi
	;;
    esac
    shift
done

if [ -z "${FILE1}" -o -z "${FILE2}" ]; then
    printf "usage: ${ME} file1.dat file2.dat > plot.pdf\n" 1>&2
    exit 1
fi

PERPAGE=`expr ${GROWS} \* ${GCOLS}`

## Make the diff file

DIFF=`mktemp diff.XXX`
${TOOLS}/diff_log ${FILE1} ${FILE2} > ${DIFF}

if [ $? -ne 0 ]; then
    printf "${ME}: an error occurred in diff_log\n" 1>&2
    exit 1
fi

COLS=`sed -e 's/[       ][      ]*/\n/g;s/"//g;q' ${FILE1}`

PLOTS=""
colnum=1
graph=0
for col in ${COLS}; do
    for mode in ${MODES}; do
	if [ ${colnum} -ne 1 ]; then
	    if [ `expr ${graph} % ${PERPAGE}` -eq 0 ]; then
		PLOTS="${PLOTS} set multiplot title '${TITLE}'"
		PLOTS="${PLOTS} layout ${GROWS},${GCOLS};"
	    fi

	    PLOTS="${PLOTS} set title '"
	    if [ ${PERPAGE} -eq 1 ]; then
		PLOTS="${PLOTS}${TITLE}: "
	    fi

	    if [ ${mode} -eq 0 ]; then
		PLOTS="${PLOTS}${col} (${FILENAME1} - ${FILENAME2})';"
		PLOTS="${PLOTS} unset key;"
		PLOTS="${PLOTS} plot '${DIFF}' using 1:${colnum} with lines;"
	    else
		PLOTS="${PLOTS}${col} (comparison)';"
		PLOTS="${PLOTS} set key;"
		PLOTS="${PLOTS} plot '${FILE1}' using 1:${colnum}"
		PLOTS="${PLOTS} with points title '${FILENAME1}',"
		PLOTS="${PLOTS}      '${FILE2}' using 1:${colnum}"
		PLOTS="${PLOTS} with points title '${FILENAME2}';"
	    fi

	    graph=`expr ${graph} + 1`
	fi
    done

    colnum=`expr ${colnum} + 1`
done

GPLOT=$(cat <<EOF
set terminal pdf font ",4" ${TERMOPTIONS};

set grid;

set lmargin 10;

${PLOTS}
EOF
)

gnuplot -e "${GPLOT}"
rm -f ${DIFF}

