#!/bin/sh

# This script plots the internal states, zero-crossings, and zero-crossing
# expressions of a zelus program, i.e., the data logged when the -l and
# -lzeroexp options are enabled.

ME=`basename $0`
COMMAND="$@"

if [ -z "${COMMAND}" ]; then
    printf "example usage: ${ME} ./prog.byte -sundialsI -maxt 10 > plot.pdf\n" 1>&2
    exit 1
fi

LOGFILE=`mktemp`
CSFILE=`mktemp`
ZCFILE=`mktemp`
ZEFILE=`mktemp`

$@ -l -lzeroexp > ${LOGFILE}

if [ ! $? ]; then
    rm -f ${LOGFILE} ${CSFILE} ${ZCFILE} ${ZEFILE}
    exit 1
fi

sed -ne 's/^[IC].: \(.*\)$/\1/p' ${LOGFILE} > ${CSFILE}
sed -ne 's/^Z.: \(.*\)$/\1/p' ${LOGFILE} > ${ZCFILE}
sed -ne 's/^U.: \(.*\)$/\1/p' ${LOGFILE} > ${ZEFILE}

# work through state columns
I=1
N=0
for c in `head -n 1 ${CSFILE}`; do
    if [ $I -eq 2 ]; then
	PLOTCS="plot '${CSFILE}' using 1:$I with lines title 'cs$N'"
    elif [ $I -gt 2 ]; then
	PLOTCS="${PLOTCS}, '' using 1:$I with lines title 'cs$N'"
    fi
    I=`expr $I + 1`
    N=`expr $N + 1`
done

# work through zero-crossing columns
I=1
N=0
for c in `head -n 1 ${ZCFILE}`; do
    if [ $I -eq 2 ]; then
	PLOTZC="plot '${ZCFILE}' using 1:(\$$I>0 ? 0 : NaN) notitle axes x1y2"
	PLOTZE="plot '${ZEFILE}' using 1:$I with lines title 'zc$N' axes x1y1"
    elif [ $I -gt 2 ]; then
	PLOTZC="${PLOTZC}, '' using 1:(\$$I>0 ? 0 : NaN) notitle axes x1y2"
	PLOTZE="${PLOTZE}, '' using 1:$I with lines title 'zc$N' axes x1y1"
    fi
    I=`expr $I + 1`
    N=`expr $N + 1`
done

GPLOT=$(cat <<EOF
set terminal pdf font ",3";

set grid;
set key top right;

set lmargin 10;

set title 'continuous states (${COMMAND})';
${PLOTCS};

set multiplot;

set title 'zero crossings (${COMMAND})';
${PLOTZE};
unset ytics;
set y2range [GPVAL_Y_MIN:GPVAL_Y_MAX];
${PLOTZC};

EOF
)

gnuplot -e "${GPLOT}"
rm -f ${LOGFILE} ${CSFILE} ${ZCFILE} ${ZEFILE}

