(include_subdirs unqualified)

; Copy config file to be included in :standard modules

(rule
 (copy %{project_root}/config.ml config.ml))

(library
 (name zelus_compiler)
 (public_name zelus.compiler)
 (wrapped false)
 (modules :standard \ zeluc)
 (libraries unix menhirLib))

(executable
 (name zeluc)
 (modes
  (byte exe))
 (libraries unix zelus_compiler)
 (preprocess
  (pps ppx_deriving.show))
 (modules zeluc)
 (promote
  (until-clean)
  (into %{project_root}/bin)))
