all:
	dune build -- zeluc.exe

debug:
	dune build --debug-backtraces --debug-dependency-path -- zeluc.bc

#OCAMLRUNPARAM=b dune exec zeluc.bc --profile=dev -- "arguments de zeluc.bc"

clean:
	dune clean

