name: Build

on:
  - push
  - pull_request
  - workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        solver:
          - nosundials
        plot:
          - nogtk
        ocaml-version:
          - 5.2.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
        
      - name: Install OCaml dependencies
        run: opam install -y graphics menhir alcotest

      - name: Install Sundials
        if: matrix.solver == 'sundials'
        run: opam depext conf-sundials

      - name: Install Sundials/ML
        if: matrix.solver == 'sundials'
        run: opam install sundialsml

      - name: Install Zelus
        run: |
          opam pin -y -n -k path .
          opam install -y zelus

      - name: Install Gtk
        if: matrix.plot == 'gtk'
        run: opam install -y zelus-gtk
