name: Opam

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.1
            
      - name: Install OCaml dependencies
        run: |
          opam depext sundialsml
          opam install graphics sundialsml zelus zelus-gtk
      
      - name: Build all examples
        run: |
          cd examples 
          opam exec -- dune build --root .
