name: Opam

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install external dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc wget cmake gtk2.0
        
      - name: Use OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.11.1
        
      - name: Install OCaml dependencies
        run: opam install -y graphics sundialsml zelus zelus-gtk
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build all examples
        run: |
          cd examples 
          opam exec -- dune build --root .
