#!/bin/sh

ME=`basename $0`
DATAFILE="$1"

if [ -z "${DATAFILE}" ]; then
    printf "usage: ${ME} file.out > plot.pdf\n" 1>&2
    exit 1
fi

GPLOT=$(cat <<EOF
set terminal pdf font ",4";

set grid;
unset key;

set multiplot title 'Clutch model (${DATAFILE})' layout 2,1;
set lmargin 10;

set xlabel 'Time';
set key top right;

set title 'Inputs';
set ylabel 'Engine torque and Frictions from Clutch Normal Force';
set yrange [0:2.1];

set key autotitles columnhead;

plot '${DATAFILE}'
	using 1:2 with lines,
     '' using 1:3 with lines,
     '' using 1:4 with lines;

set title 'Outputs';
set ylabel 'Engine, Vehicle and Shaft speeds';
set yrange [0:0.8];
plot '${DATAFILE}'
	using 1:5 with lines,
     '' using 1:6 with lines,
     '' using 1:7 with lines;

EOF
)

gnuplot -e "${GPLOT}"

